name: runDiawi

on:
  push:
    branches: [test]

jobs:
  runDiawi:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install bundle
        run: |
          cd android
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Distribute app with 🔥 App Distribution 🚀
        run: |
          npm install
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          cd android
          bundle exec fastlane runDiawi
