name: diawi

on:
  push:
    branches: [test]

jobs:
  distribute:
  diawi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.3'

      - name: Install bundle
        run: |
          gem update
          BUNDLE_GEMFILE="./Gemfile" bundle install